# Generated by Django 5.0.2 on 2026-02-05 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Депозит'), ('bet', 'Ставка'), ('win', 'Выигрыш'), ('bonus', 'Бонус')], max_length=10, verbose_name='Тип транзакции')),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Баланс до')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Баланс после')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('completed', 'Завершена'), ('failed', 'Ошибка')], default='completed', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'db_table': 'transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='user_created_idx'), models.Index(fields=['transaction_type', 'status'], name='type_status_idx')],
            },
        ),
    ]
