# Generated by Django 5.0.2 on 2026-02-05 22:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MinesGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма ставки')),
                ('mine_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(20)], verbose_name='Количество мин')),
                ('state', models.CharField(choices=[('active', 'Активна'), ('won', 'Выиграна'), ('lost', 'Проиграна'), ('cashed_out', 'Забрана')], default='active', max_length=20, verbose_name='Состояние игры')),
                ('opened_cells', models.JSONField(default=list, help_text='Список [row, col] открытых клеток', verbose_name='Открытые клетки')),
                ('current_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=8, verbose_name='Текущий множитель')),
                ('server_seed', models.CharField(help_text='Секретный seed сервера (64 hex chars)', max_length=64, verbose_name='Server seed')),
                ('client_seed', models.CharField(help_text='Публичный seed клиента (64 hex chars)', max_length=64, verbose_name='Client seed')),
                ('nonce', models.IntegerField(default=0, help_text='Номер раунда для данной пары seeds', verbose_name='Nonce')),
                ('server_seed_hash', models.CharField(help_text='SHA256 хэш server_seed (показывается до игры)', max_length=64, verbose_name='Server seed hash')),
                ('mine_positions', models.JSONField(blank=True, help_text='Список [row, col] позиций мин (раскрывается после игры)', null=True, verbose_name='Позиции мин')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершена')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mines_games', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Игра Mines',
                'verbose_name_plural': 'Игры Mines',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='mines_user_created_idx'), models.Index(fields=['state'], name='mines_state_idx')],
            },
        ),
    ]
