# Generated by Django 5.0.2 on 2026-02-05 23:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlinkoGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма ставки')),
                ('row_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(16)], verbose_name='Количество рядов')),
                ('risk_level', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], max_length=10, verbose_name='Уровень риска')),
                ('final_multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Финальный множитель')),
                ('ball_path', models.JSONField(blank=True, help_text='Список 0/1 для left/right на каждом ряду', null=True, verbose_name='Путь шарика')),
                ('bucket_index', models.IntegerField(blank=True, help_text='Финальная корзина (0 to row_count)', null=True, verbose_name='Индекс корзины')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plinko_games', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Игра Plinko',
                'verbose_name_plural': 'Игры Plinko',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='plinko_user_created_idx')],
            },
        ),
    ]
