# Generated by Django 5.0.2 on 2026-02-05 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_plinkogame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plinkogame',
            name='row_count',
            field=models.IntegerField(help_text='Допустимые значения: 5, 9, 11, 13, 15', verbose_name='Количество рядов'),
        ),
    ]
