# Generated by Django 5.0.2 on 2026-02-06 16:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_plinkogame_row_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiceGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма ставки')),
                ('selected_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Выбранное число')),
                ('rolled_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Выпавшее число')),
                ('multiplier', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Множитель')),
                ('won', models.BooleanField(default=False, verbose_name='Выиграл')),
                ('server_seed', models.CharField(help_text='Секретный seed сервера (64 hex chars)', max_length=64, verbose_name='Server seed')),
                ('client_seed', models.CharField(help_text='Публичный seed клиента (64 hex chars)', max_length=64, verbose_name='Client seed')),
                ('nonce', models.IntegerField(default=0, help_text='Номер раунда для данной пары seeds', verbose_name='Nonce')),
                ('server_seed_hash', models.CharField(help_text='SHA256 хэш server_seed (показывается до игры)', max_length=64, verbose_name='Server seed hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dice_games', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Игра Dice',
                'verbose_name_plural': 'Игры Dice',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='dice_user_created_idx')],
            },
        ),
    ]
