# Generated by Django 5.0.2 on 2026-02-07 10:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_dicegame'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotsGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма ставки')),
                ('reels_count', models.IntegerField(choices=[(3, '3 барабана'), (5, '5 барабанов')], default=5, verbose_name='Количество барабанов')),
                ('reels', models.JSONField(help_text='Массив из 3 или 5 символов', verbose_name='Барабаны')),
                ('multiplier', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Множитель')),
                ('win_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма выигрыша')),
                ('winning_combination', models.CharField(blank=True, max_length=100, verbose_name='Выигрышная комбинация')),
                ('server_seed', models.CharField(help_text='Секретный seed сервера (64 hex chars)', max_length=64, verbose_name='Server seed')),
                ('client_seed', models.CharField(help_text='Публичный seed клиента (64 hex chars)', max_length=64, verbose_name='Client seed')),
                ('nonce', models.IntegerField(default=0, help_text='Номер раунда для данной пары seeds', verbose_name='Nonce')),
                ('server_seed_hash', models.CharField(help_text='SHA256 хэш server_seed (показывается до игры)', max_length=64, verbose_name='Server seed hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots_games', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Игра Slots',
                'verbose_name_plural': 'Игры Slots',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='slots_user_created_idx')],
            },
        ),
    ]
