# Generated by Django 5.0.2 on 2026-02-07 22:50

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_slotsgame'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrashRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID раунда')),
                ('status', models.CharField(choices=[('waiting', 'Ожидание'), ('active', 'Активен'), ('crashed', 'Крашнулся')], default='waiting', max_length=20, verbose_name='Статус')),
                ('crash_point', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Точка краша')),
                ('server_seed', models.CharField(help_text='Секретный seed сервера (64 hex chars)', max_length=64, verbose_name='Server seed')),
                ('client_seed', models.CharField(help_text='Публичный seed клиента (64 hex chars)', max_length=64, verbose_name='Client seed')),
                ('server_seed_hash', models.CharField(help_text='SHA256 хэш server_seed (показывается до игры)', max_length=64, verbose_name='Server seed hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начат')),
                ('crashed_at', models.DateTimeField(blank=True, null=True, verbose_name='Крашнулся')),
                ('next_round_at', models.DateTimeField(blank=True, null=True, verbose_name='Следующий раунд')),
            ],
            options={
                'verbose_name': 'Раунд Crash',
                'verbose_name_plural': 'Раунды Crash',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='crash_round_status_idx'), models.Index(fields=['-created_at'], name='crash_round_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='CrashBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма ставки')),
                ('cashout_multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Множитель кэшаута')),
                ('win_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Сумма выигрыша')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('cashed_out', 'Забрана'), ('lost', 'Проиграна')], default='active', max_length=20, verbose_name='Статус')),
                ('auto_cashout_target', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.01'))], verbose_name='Цель авто-кэшаута')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('cashed_out_at', models.DateTimeField(blank=True, null=True, verbose_name='Забрана')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crash_bets', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='games.crashround', verbose_name='Раунд')),
            ],
            options={
                'verbose_name': 'Ставка Crash',
                'verbose_name_plural': 'Ставки Crash',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'round'], name='crash_bet_user_round_idx'), models.Index(fields=['round', 'status'], name='crash_bet_round_status_idx'), models.Index(fields=['round', 'status', 'auto_cashout_target'], name='crash_bet_auto_cashout_idx')],
            },
        ),
    ]
